FROM php:8.1.1-apache
RUN apt-get update
RUN apt-get install -y zip
RUN apt-get install -y git
RUN apt-get install -y zlib1g-dev
RUN apt-get install -y libpng-dev
RUN docker-php-ext-install gd

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
ENV COMPOSER_ALLOW_SUPERUSER=1
RUN composer create-project drupal/recommended-project /var/www/html
COPY 000-default.conf /etc/apache2/sites-available/
RUN mkdir /var/www/html/web/sites/default/files/
RUN mkdir /var/www/html/web/sites/default/files/translations
RUN chmod 777 -R /var/www/html/web/sites/default/files/
RUN cp /var/www/html/web/sites/default/default.settings.php  /var/www/html/web/sites/default/settings.php
RUN chmod 777 /var/www/html/web/sites/default/settings.php